Add an argument to the parent class to allow for numbers in the string.
mehmedkadric/random-string-detector pull request #3
Opened 2024-01-04 17:07 UTC by ryankelly-klaviyo

This is useful when validating a username for randomness, as legitimate usernames can have numbers present. I need this additoinal functionality for validating usernames.

2024-01-04 17:08 UTC, ryankelly-klaviyo commented
(sorry for the closing/reopening)

2024-01-12 01:29 UTC, mehmedkadric commented
Hi Ryan, thanks for initiative!

Could you please create test and add usage example to README.md for your proposed functionality?

2024-02-06 09:09 UTC, mehmedkadric requested changes
Please add tests.

2024-03-12 00:52 UTC, mehmedkadric approved these changes

2024-03-12 00:53 UTC, merged